[package]
name = "ferrumc"
version = "0.1.1"
edition = "2021"
build = "build/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async
tokio = { version = "1.38.0", features = ["full", "tracing"] }
futures = "0.3.30"
async-trait = "0.1.77"

# Error handling
anyhow = "1.0.86"
thiserror = "1.0.61"

# Logging
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
console-subscriber = "0.4.0"

# Serialization / Deserialization
serde = { version = "1.0.203", features = ["derive"] }
serde_derive = "1.0.209"
serde_json = "1.0.119"
toml = "0.8.14"
flexbuffers = "2.0.0"
bincode = "2.0.0-rc.3"

# Configuration
config = "0.14.0"
lazy_static = "1.4.0"

# NBT and Anvil
fastnbt = "2.5.0"
fastanvil = "0.31.0"
simdnbt = { path = "src/crates/yoinked/simdnbt/simdnbt" }
simdnbt-derive = { path = "src/crates/yoinked/simdnbt/simdnbt-derive" }

# Binary
byteorder = "1.5.0"
uuid = { version = "1.9.1", features = ["v4", "v3", "v5"] }

# Compression
include-flate = "0.3.0"
flate2 = { version = "1.0.31", features = ["zlib"] }
bzip2 = "0.4.4"
lz4_flex = "0.11.3"
zstd = "0.13.2"

# OS
which = "6.0.1"

# Custom crates
ferrumc_macros = { path = "src/crates/ferrumc_macros" }
ferrumc_codec = { path = "src/crates/ferurmc_codec" }
nbt-lib = { path = 'src/crates/nbt-workspace/nbt-lib', features = ["derive"] }

# Database
moka = { version = "0.12.8", features = ["future"] }
heed = "0.20.5"

# Misc
dashmap = "6.0.1"
hashbrown = { version = "0.14.5", features = ["serde"] }
rand = "0.9.0-alpha.1"
base64 = "0.22.1"
rayon = "1.10.0"
macro_rules_attribute = "0.2.0"
deepsize = "0.2.0"
deepsize_derive = "0.1.2"

# CLI
clap = { version = "4.5.11" }
clap_derive = "4.5.11"
indicatif = "0.17.8"
num_cpus = "1.16.0"


# Set the cache to the highest level for development
[profile.dev.package.moka]
opt-level = 3

[lib]
name = "ferrumc"
path = "src/lib.rs"

[[bin]]
name = "ferrumc"
path = "src/main.rs"

[build-dependencies]
# Build
winres = "0.1.12"

[dev-dependencies]
# Benches
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benches"
harness = false
path = "./src/benches/bench_nbt_ser_de.rs"
